services:
  db:
    container_name: rurik_staging_db

  auth-service:
    image: ghcr.io/tytosmag/rurikcode.ru/auth-service:staging
    container_name: rurik_staging_auth

  leaderboard-service:
    image: ghcr.io/tytosmag/rurikcode.ru/leaderboard-service:staging
    container_name: rurik_staging_leaderboard

  game-service:
    image: ghcr.io/tytosmag/rurikcode.ru/game-service:staging
    container_name: rurik_staging_game

  client:
    image: ghcr.io/tytosmag/rurikcode.ru/client:staging
    container_name: rurik_staging_client
    expose:
      - "80"

  gateway:
    container_name: rurik_staging_gateway
    ports:
      - "${GATEWAY_HTTP_PORT:-8080}:80"
    volumes:
      - ./gateway/nginx.prod.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
    name: rurik_staging_postgres_data